// constants/meeting.constants.ts

import { Meeting, TagInfo } from "@/types/meeting.types";

export const DUMMY_MEETINGS: Meeting[] = [
  {
    id: "1",
    title: "Q1 Product Strategy Review",
    timestamp: new Date("2024-01-15T10:00:00"),
    duration: 45,
    participants: ["Sarah Chen", "Mike Johnson", "Emily Davis", "Alex Turner"],
    tags: ["Strategy", "Product", "Q1"],
    isFavorite: true,
    transcript: "Sarah: Let's start by reviewing our Q1 objectives... Mike: I think we need to focus on user retention... Emily: The analytics show promising results...",
    summary: "Discussed Q1 product strategy focusing on user retention and feature prioritization. Team agreed to implement three key features by end of quarter.",
    translations: [
      { language: "Spanish", content: "Discutimos la estrategia de producto del Q1..." },
      { language: "French", content: "Nous avons discuté de la stratégie produit Q1..." },
    ],
    actionItems: [
      { text: "Finalize feature roadmap", assignee: "Sarah Chen", completed: true },
      { text: "Schedule user research sessions", assignee: "Emily Davis", completed: false },
      { text: "Review budget allocation", assignee: "Mike Johnson", completed: false },
    ],
  },
  {
    id: "2",
    title: "Engineering Sprint Planning",
    timestamp: new Date("2024-01-18T14:30:00"),
    duration: 60,
    participants: ["Alex Turner", "David Kim", "Rachel Martinez", "Tom Wilson", "Sarah Chen"],
    tags: ["Engineering", "Sprint", "Planning"],
    isFavorite: false,
    transcript: "Alex: Today we're planning sprint 24... David: I suggest we tackle the authentication refactor... Rachel: We also need to address the performance issues...",
    summary: "Sprint 24 planning completed. Team committed to 23 story points including authentication refactor and performance optimizations.",
    translations: [
      { language: "German", content: "Sprint 24 Planung abgeschlossen..." },
    ],
    actionItems: [
      { text: "Create tickets for authentication refactor", assignee: "David Kim", completed: true },
      { text: "Set up performance monitoring", assignee: "Rachel Martinez", completed: true },
      { text: "Update project timeline", assignee: "Alex Turner", completed: false },
    ],
  },
  {
    id: "3",
    title: "Customer Feedback Session",
    timestamp: new Date("2024-01-20T11:00:00"),
    duration: 30,
    participants: ["Emily Davis", "Jessica Brown"],
    tags: ["Customer", "Feedback", "UX"],
    isFavorite: true,
    transcript: "Emily: Thank you for joining us today... Jessica: The main pain point we're experiencing is... Emily: That's very valuable feedback...",
    summary: "Gathered important feedback from enterprise customer. Key issues identified around onboarding flow and reporting features.",
    translations: [],
    actionItems: [
      { text: "Design improved onboarding flow", assignee: "Emily Davis", completed: false },
      { text: "Prototype new reporting dashboard", assignee: "Emily Davis", completed: false },
    ],
  },
  {
    id: "4",
    title: "Marketing Campaign Kickoff",
    timestamp: new Date("2024-01-22T09:00:00"),
    duration: 75,
    participants: ["Lisa Anderson", "Mike Johnson", "Sarah Chen", "Tom Wilson", "Rachel Martinez", "David Kim"],
    tags: ["Marketing", "Campaign", "Launch"],
    isFavorite: false,
    transcript: "Lisa: Welcome everyone to the campaign kickoff... Mike: Our target is to increase brand awareness by 40%... Sarah: I've prepared the creative brief...",
    summary: "Kicked off new marketing campaign targeting enterprise segment. Budget approved, timeline set for 8-week campaign.",
    translations: [
      { language: "Portuguese", content: "Iniciamos nova campanha de marketing..." },
    ],
    actionItems: [
      { text: "Finalize creative assets", assignee: "Lisa Anderson", completed: true },
      { text: "Set up tracking pixels", assignee: "Tom Wilson", completed: true },
      { text: "Schedule social media posts", assignee: "Rachel Martinez", completed: false },
      { text: "Prepare press release", assignee: "Mike Johnson", completed: false },
    ],
  },
  {
    id: "5",
    title: "Weekly Team Standup",
    timestamp: new Date("2024-01-23T10:00:00"),
    duration: 15,
    participants: ["Alex Turner", "David Kim", "Rachel Martinez"],
    tags: ["Standup", "Engineering"],
    isFavorite: false,
    transcript: "Alex: Let's go around. David, what did you work on? David: I completed the API integration... Rachel: I'm working on the frontend components...",
    summary: "Quick team sync. All tasks on track. Minor blocker identified and resolved.",
    translations: [],
    actionItems: [
      { text: "Review pull requests", assignee: "Alex Turner", completed: true },
    ],
  },
  {
    id: "6",
    title: "Board Meeting - January",
    timestamp: new Date("2024-01-25T15:00:00"),
    duration: 120,
    participants: ["Sarah Chen", "Mike Johnson", "Jennifer Lee", "Robert Taylor", "Michael Brown"],
    tags: ["Board", "Executive", "Financials"],
    isFavorite: true,
    transcript: "Sarah: Thank you all for joining today's board meeting... Jennifer: The financial results are strong... Robert: What about the hiring plan?...",
    summary: "Presented Q4 results to board. Revenue exceeded targets by 15%. Approved hiring plan for 20 new positions.",
    translations: [
      { language: "Mandarin", content: "向董事会展示了第四季度业绩..." },
    ],
    actionItems: [
      { text: "Finalize hiring budget", assignee: "Sarah Chen", completed: true },
      { text: "Schedule investor update", assignee: "Mike Johnson", completed: false },
      { text: "Prepare Q1 forecast", assignee: "Jennifer Lee", completed: false },
    ],
  },
  {
    id: "7",
    title: "Design System Workshop",
    timestamp: new Date("2024-01-26T13:00:00"),
    duration: 90,
    participants: ["Emily Davis", "Rachel Martinez", "Tom Wilson", "Lisa Anderson"],
    tags: ["Design", "Workshop", "UX"],
    isFavorite: false,
    transcript: "Emily: Today we'll establish our design system principles... Rachel: I think consistency is key... Tom: What about accessibility?...",
    summary: "Established core design system principles. Created component library structure. Set accessibility standards.",
    translations: [],
    actionItems: [
      { text: "Document design tokens", assignee: "Emily Davis", completed: false },
      { text: "Create Figma component library", assignee: "Rachel Martinez", completed: false },
      { text: "Audit current components", assignee: "Tom Wilson", completed: true },
    ],
  },
  {
    id: "8",
    title: "Sales Team Training",
    timestamp: new Date("2024-01-29T10:30:00"),
    duration: 60,
    participants: ["Mike Johnson", "Jessica Brown", "Robert Taylor", "Lisa Anderson", "Tom Wilson"],
    tags: ["Sales", "Training", "Enablement"],
    isFavorite: false,
    transcript: "Mike: Welcome to product training session... Jessica: Can you explain the new pricing model? Mike: Absolutely, let me walk you through it...",
    summary: "Trained sales team on new product features and updated pricing. Provided demo scripts and objection handling guide.",
    translations: [],
    actionItems: [
      { text: "Distribute training materials", assignee: "Mike Johnson", completed: true },
      { text: "Schedule follow-up Q&A", assignee: "Lisa Anderson", completed: false },
    ],
  },
];

export const AVAILABLE_TAGS: TagInfo[] = [
  { name: "Strategy", color: "bg-blue-500" },
  { name: "Product", color: "bg-purple-500" },
  { name: "Engineering", color: "bg-green-500" },
  { name: "Marketing", color: "bg-pink-500" },
  { name: "Sales", color: "bg-orange-500" },
  { name: "Design", color: "bg-indigo-500" },
  { name: "Customer", color: "bg-teal-500" },
  { name: "Executive", color: "bg-red-500" },
  { name: "Q1", color: "bg-yellow-500" },
  { name: "Sprint", color: "bg-cyan-500" },
];